package com.devartlab.model

import com.devartlab.data.room.tradedetails.TradeDetailsEntity
import kotlin.collections.ArrayList

data class InvTrxSalesPurchaseModel  (
        val InvoiceId  : Int? = null,
        val InvoiceSerial: String? = null,
        val InvoiceTypeId  : Int? = null,
        val InvoiceNatural  : Int? = null,
        val InvoiceCreateDate: String? = null,
        val InvoiceDueDate: String? = null,
        val InvoiceDueDays  : Int? = null,
        val InvoiceDescription: String? = null,
        val CustomerId  : Int? = null,
        val StoreId  : Int? = null,
        val SuppId  : Int? = null,
        val SuppInvoiceSerial: String? = null,
        val AddUserId  : Int? = null,
        val AddEmpId  : Int? = null,
        val AddMAc: String? = null,
        val AddDateTime: String? = null,
        val ModifyUserId  : Int? = null,
        val ModifyEmpId  : Int? = null,
        val ModifyMac: String? = null,
        val ModifyDatetime: String? = null,
        val TotalInvoiceBeforDiscount: Double? = null,
        val TotalInvoiceDiscount: Double? = null,
        val TotalInvoiceWithoutTax: Double? = null,
        val TotalInvoiceTax: Double? = null,
        val TotalInvoiceWithTax: Double? = null,
        val TotalAddDiscAccounts: Double? = null,
        val TotalInvoiceNet: Double? = null,
        val JournalId  : Int? = null,
        val StoreTrxTypeId  : Int? = null,
        val InventoryTrxId  : Int? = null,
        val VOucherId  : Int? = null,
        val ISPayed: Boolean? = null,
        val TotalPaid: Double? = null,
        val TotalReminder: Double? = null,
        val Empid  : Int? = null,
        val ContractId  : Int? = null,
        val TrxAutoSerial  : Int? = null,
        val Approved: Double? = null,
        val ApprovedByUserId  : Int? = null,
        val ApprovedByEmpId  : Int? = null,
        val ApprovedByMAc: String? = null,
        val ApprovedByDateTime: String? = null,
        val ApprovedNotes: String? = null,
        val CopyFromTrxSerialStr: String? = null,
        val AdditionalDisc1Value: Double? = null,
        val AdditionalDisc2Value: Double? = null,
        val AdditionalDisc3Value: Double? = null,
        val CashDiscValue: Double? = null,
        val TotalAllocationCost: Double? = null,
        val AllocationCostJournal  : Int? = null,
        val LandedCostSupplierIdStr: String? = null,
        val SuppIdStr: String? = null,
        val Closed: Double? = null,
        val ClosedByUserId  : Int? = null,
        val ClosedByEmpId  : Int? = null,
        val ClosedByMAc: String? = null,
        val ClosedByDateTime: String? = null,
        val ClosedNotes: String? = null,
        val IsAccumulative: Double? = null,
        val ExpireDate: String? = null,
        val DLInvTrxSalesPurchaseDetails: ArrayList<TradeDetailsEntity>? = null,
        val DLInvTrxSalesPurchaseAddDiscDetails: ArrayList<Object>? = null,
        val DLInvTrxSalesPurchaseServiceFeesDetails: ArrayList<Object>? = null,
        val DLInvTrxSalesPurchaseCostCenter: ArrayList<Object>? = null,
        val IsDraft: Boolean = false
)